; PlatformIO Project Configuration File for FZ8 Dynamics Telemetry
; Microcontroller: ESP32-C3 DevKitM-1 (RISC-V)

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BMP085 Library@^1.2.4
